name = "FreeType"
uuid = "b38be410-82b0-50bf-ab77-7b57e271db43"
version = "4.1.2"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"

[compat]
CEnum = "0.2,0.3,0.4,0.5"
FreeType2_jll = "2.13.4"
julia = "1.3"
Cairo = "1.1"
Images = "0.25, 0.26"
Downloads = "1"

[extras]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[targets]
test = ["Test", "Pkg", "Images", "Cairo", "Downloads"]
